version: "3.9"

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        image: php:7-fpm-alpine
        volumes:
            - .:/var/www/html
            - ./dir2cast.php:/dir2cast.php
            - ./getID3:/getID3
            - /tmp:/temp
